package com.example.keyboardShorcuts.model

object Constants {
    val listOfPrograms = listOf<Programs>(
        Programs("Figma", "figma.json"),
        Programs("Android Studio", "android-studio.json"),
        Programs("1Password", "1password.json"),
        Programs("Adobe Lightroom CC", "adobe-lightroom.json"),
        Programs("Adobe Photoshop", "adobe-photoshop.json"),
        Programs("Adobe XD", "adobe-xd.json"),
        Programs("Affinity Designer", "affinity-designer.json"),
        Programs("Affinity Photo", "affinity-photo.json"),
        Programs("Airtable", "airtable.json"),
        Programs("Apex Legends", "apex-legends.json"),
        Programs("Arduino IDE", "arduino.json"),
        Programs("Asana", "asana.json"),
        Programs("Audacity", "audacity.json"),
        Programs("Bear", "bear-notes.json"),
        Programs("Bitbucket", "bitbucket.json"),
        Programs("Blender", "blender.json"),
        Programs("Brave Browser", "brave.json"),
        Programs("Chrome Developer Tools", "chrome-devtools.json"),
        Programs("Code Editor for iOS", "code-editor-ios.json"),
        Programs("Discord", "discord.json"),
        Programs("Dropbox", "dropbox.json"),
        Programs("Evernote", "evernote.json"),
        Programs("Excel", "excel.json"),
        Programs("FileZilla", "filezilla.json"),
        Programs("Finder", "finder.json"),
        Programs("Firefox", "firefox.json"),
        Programs("Fortnite", "fortnite.json"),
        Programs("Framer X", "framer-x.json"),
        Programs("GIMP", "gimp.json"),
        Programs("Github", "github.json"),
        Programs("GitLab", "gitlab.json"),
        Programs("Gmail", "gmail.json"),
        Programs("Google Chrome", "google-chrome.json"),
        Programs("Google Drive", "google-drive.json"),
        Programs("Guitar Pro", "guitar-pro.json"),
        Programs("iTerm", "iterm.json"),
        Programs("Jira", "jira.json"),
        Programs("KanbanMail", "kanbanmail.json"),
        Programs("Microsoft Teams", "microsoft-teams.json"),
        Programs("Missive", "missive.json"),
        Programs("Monday.com", "monday.json"),
        Programs("Netflix", "netflix.json"),
        Programs("Notepad++", "notepad-plus-plus.json"),
        Programs("Notion", "notion.json"),
        Programs("Obsidian", "obsidian.json"),
        Programs("Origami Studio", "origami.json"),
        Programs("Microsoft Outlook", "outlook.json"),
        Programs("PhpStorm", "phpstorm.json"),
        Programs("Postman", "postman.json"),
        Programs("Principle", "principle.json"),
        Programs("Proto.io", "proto-io.json"),
        Programs("PuTTy", "putty.json"),
        Programs("Quip.com", "quip.json"),
        Programs("Reddit", "reddit.json"),
        Programs("Roam Research", "roam.json"),
        Programs("Shopify", "shopify.json"),
        Programs("Sketch", "sketch.json"),
        Programs("SketchUp Pro", "sketchup.json"),
        Programs("Sequel Pro", "sequelpro.json"),
        Programs("Skype", "skype.json"),
        Programs("Slack", "slack.json"),
        Programs("SoundCloud", "soundcloud.json"),
        Programs("Spotify", "spotify.json"),
        Programs("Sublime Text", "sublime-text.json"),
        Programs("Superhuman", "superhuman.json"),
        Programs("TablePlus", "tableplus.json"),
        Programs("Telegram Desktop", "telegram.json"),
        Programs("TickTick", "ticktick.json"),
        Programs("Todoist", "todoist.json"),
        Programs("Transmit", "transmit.json"),
        Programs("Trello", "trello.json"),
        Programs("Twitter", "twitter.json"),
        Programs("Unity 3D", "unity-3d.json"),
        Programs("Vivaldi Browser", "vivaldi.json"),
        Programs("VLC Player", "vlc-player.json"),
        Programs("Visual Studio Code", "vs-code.json"),
        Programs("Webflow", "webflow.json"),
        Programs("WordPress", "wordpress.json"),
        Programs("Xcode", "xcode.json"),
        Programs("YouTube", "youtube.json"),
        Programs("Zoom for Mac", "zoom-mac.json"),
        Programs("Zoom for Windows", "zoom-windows.json")

    )


}