package com.example.keyboardshorcuts.model

object Constants {
    val listOfPrograms = listOf<Programs>(
        Programs("Figma"),
        Programs("Android Studio"),
        Programs("1Password"),
        Programs("Adobe Lightroom CC"),
        Programs("Adobe Photoshop"),
        Programs("Adobe XD"),
        Programs("Affinity Designer"),
        Programs("Affinity Photo"),
        Programs("Airtable"),
        Programs("Apex Legends"),
        Programs("Arduino IDE"),
        Programs("Asana"),
        Programs("Audacity"),
        Programs("Bear"),
        Programs("Bitbucket"),
        Programs("Blender"),
        Programs("Brave Browser"),
        Programs("Chrome Developer Tools"),
        Programs("Code Editor for iOS"),
        Programs("Discord"),
        Programs("Dropbox"),
        Programs("Evernote"),
        Programs("Excel"),
        Programs("FileZilla"),
        Programs("Finder"),
        Programs("Firefox"),
        Programs("Fortnite"),
        Programs("Framer X"),
        Programs("GIMP"),
        Programs("Github"),
        Programs("GitLab"),
        Programs("Gmail"),
        Programs("Google Chrome"),
        Programs("Google Drive"),
        Programs("Guitar Pro"),
        Programs("iTerm"),
        Programs("Jira"),
        Programs("KanbanMail"),
        Programs("Microsoft Teams"),
        Programs("Missive"),
        Programs("Monday.com"),
        Programs("Netflix"),
        Programs("Notepad++"),
        Programs("Notion"),
        Programs("Obsidian"),
        Programs("Origami Studio"),
        Programs("Microsoft Outlook"),
        Programs("PhpStorm"),
        Programs("Postman"),
        Programs("Principle"),
        Programs("Proto.io"),
        Programs("PuTTy"),
        Programs("Quip.com"),
        Programs("Reddit"),
        Programs("Roam Research"),
        Programs("Shopify"),
        Programs("Sketch"),
        Programs("Slack"),
        Programs("SoundCloud"),
        Programs("Spotify"),
        Programs("Sublime Text"),
        Programs("Superhuman"),
        Programs("TablePlus"),
        Programs("Telegram Desktop"),
        Programs("TickTick"),
        Programs("Todoist"),
        Programs("Transmit"),
        Programs("Trello"),
        Programs("Twitter"),
        Programs("Unity 3D"),
        Programs("Vivaldi Browser"),
        Programs("VLC Player"),
        Programs("Visual Studio Code"),
        Programs("Webflow"),
        Programs("WordPress"),
        Programs("Xcode"),
        Programs("YouTube"),
        Programs("Zoom for Mac"),
        Programs("Zoom for Windows")

    )
}